### ISSUE TITLE
how to set path ignore request logger

### ISSUE THREAD

**Issue by dcboy** [koajs/bunyan-logger#18]
how can i config set any spec path to ignore request logger?

**Comment by dcboy** [comment]
@landau i have upgrade this feature at https://github.com/dcboy/bunyan-logger/tree/2x

**Comment by landau** [comment]
Nice, @dcboy . Send a PR! Though, likely hood of merging into this repo seems unlikely since the owner hasn't responded to activity here.

**Comment by oleg-koval** [comment]
need to have this feature in `koa-bunyan-logger`, is there somebody to merge/release this?

**Comment by sjmcdowall** [comment]
Closed with Merge of PR #21
