### ISSUE TITLE
Add Typescript definition file

### ISSUE THREAD

**Issue by sjmcdowall** [koajs/bunyan-logger#19]
I am using Typescript in my Koa project and want to use bunyan logging -- when I import the module Typescript is complaining of a missing definition's file (because -- well -- one is).  Any chance we can add such a file?

**Comment by jlai** [comment]
No plans at the moment unless someone contributes one. According to https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html for non-TypeScript projects it's preferable to have a separate package published to @types

**Comment by sjmcdowall** [comment]
BTW -- I did submit and added a TS file to @types .. so it's there

**Comment by landau** [comment]
> No plans at the moment unless someone contributes one. According to typescriptlang.org/docs/handbook/declaration-files/publishing.html for non-TypeScript projects it's preferable to have a separate package published to @types

I disagree with this sentiment because it's easy to forget about the types. For instance,  the `ignorePath` option is missing on `RequestLoggerOptions` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c571148c8751daccabbcb639f3ae20ac83351111/types/koa-bunyan-logger/index.d.ts#L31
