### ISSUE TITLE
Just curious as to why Branch - 2 -- after 2+ years isn't the new master

### ISSUE THREAD

**Issue by sjmcdowall** [koajs/bunyan-logger#22]
And the current Master tagged Koa-1 or something?  It's very weird and unusual not to have the latest NPM published version NOT be master.  This is rather odd to me.

**Comment by oleg-koval** [comment]
![giphy 4](https://user-images.githubusercontent.com/5700359/46135065-a06f1800-c244-11e8-9ed5-0f8bf647f689.gif)

**Comment by sjmcdowall** [comment]
I wish owners of repos like thjis would add more people to the contributor list if they plan to abandon the project or let it linger.  I wonder if there is someway to "force" adding more people or something?

**Comment by aheckmann** [comment]
@sjmcdowall would you like to be added as a maintainer?

**Comment by aheckmann** [comment]
done. thanks!

**Comment by sjmcdowall** [comment]
Unless someone objects -- I am going to move the 2x branch to master and tag the old master as 1X ..
