### ISSUE TITLE
Add semantic-release

### ISSUE THREAD

**Issue by oleg-koval** [koajs/bunyan-logger#23]

**Comment by sjmcdowall** [comment]
Not exactly sure what this item means...

**Comment by sjmcdowall** [comment]
@oleg-koval -- Hey Ed, just wondering what this means and how do we close it.  Would be nice to have a 0 issue Repo!  :)

**Comment by oleg-koval** [comment]
we can use `semantic-release-cli`, can pick up it on weekend

**Comment by oleg-koval** [comment]
Unfortunately, I have no permissions to add tokens for npm & gh with https://github.com/semantic-release/cli
if Admins are interested I can add this tool, if not - that's not a big deal
