### ISSUE TITLE
Add package-lock.json

### ISSUE THREAD

**Issue by oleg-koval** [koajs/bunyan-logger#26]
package-lock.json is automatically generated for any operations where npm modifies either the node_modules tree, or package.json. It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.

**This file is intended to be committed into source repositories**, and serves various purposes:

Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.

Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.

To facilitate greater visibility of tree changes through readable source control diffs.

And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package. It shares a format with npm-shrinkwrap.json(5), which is essentially the same file, but allows publication. This is not recommended unless deploying a CLI tool or otherwise using the publication process for producing production packages.

If both package-lock.json and npm-shrinkwrap.json are present in the root of a package, package-lock.json will be completely ignored.

**Comment by sjmcdowall** [comment]
Yes -- good idea here too to get things organized!  Maybe combine this with the "update" deps item?

**Comment by oleg-koval** [comment]
@sjmcdowall I am planning to add some integration for auto-updating deps (that tool will create PRs with updates)

**Comment by oleg-koval** [comment]
@sjmcdowall unfortunately I have no rights to add any integrations to this repo, so we need some help with this from other guys :)

**Comment by sjmcdowall** [comment]
@oleg-koval -- What exactly needs to be done to add that sort of integration?!  I've never added Greenkeeper  or anything before...

**Comment by oleg-koval** [comment]
@sjmcdowall 
So GH is moving slowly to GitApps, it should be enabled from Repo Settings page, that's it for the start
