### ISSUE TITLE
Need to update readme.md to add new option for ignorePaths

### ISSUE THREAD

**Issue by sjmcdowall** [koajs/bunyan-logger#28]
We need to add the ignorePaths option and example to the documentation before we release...

**Comment by oleg-koval** [comment]
@sjmcdowall I've added some simple text to docs, but it can be better I think https://github.com/koajs/bunyan-logger/blob/master/README.md#ignoring-specific-path-from-logging

**Comment by sjmcdowall** [comment]
Oh that looks pretty good!
