### ISSUE TITLE
Can't publish to NPM

### ISSUE THREAD

**Issue by sjmcdowall** [koajs/bunyan-logger#32]
@aheckmann or @jlai  --

@oleg-koval and I (Mostly Ed!) have a new release ready for NPM.  However, we don't have the authority to push a new release.  :( 

Can someone fix this so we can actually publish the release?  My NPM login in sjmcdowall   not sure what Ed's (oleg-koval) is .

Thanks!

**Comment by oleg-koval** [comment]
my npm login is `olegkoval`

**Comment by jlai** [comment]
@sjmcdowall @oleg-koval I've added you as maintainers to the npm package. Hopefully that allows you to publish (you'll need 2FA enabled to publish).

**Comment by oleg-koval** [comment]
All good! thanks @jlai
