### ISSUE TITLE
updateLogFields mutates ctx

### ISSUE THREAD

**Issue by zacanger** [koajs/bunyan-logger#36]
For security reasons I'd like to not log cookie headers. Since `updateLogFields` mutates `ctx`, this means I end up stripping headers from requests -- and I need those, just not in the logs. Would you be open to a PR that deep clones `ctx` when it goes into the update functions? I have a little wrapper in my own code that strips out log fields before actually logging somewhere, but it feels like something that belongs in the library.

**Comment by zacanger** [comment]
I'm going to close this, as we're switching to Winston.

**Comment by Jonahss** [comment]
I had the same issue. But on closer inspection, this just uses bunyan. And bunyan does the deep cloning in its serializers. So pass serializers or a bunyan instance to this module and you should be good to go.
