### ISSUE TITLE
Is this repository still being maintained?

### ISSUE THREAD

**Issue by chipironcin** [koajs/bunyan-logger#43]
Hello,

I'd like to know if this repository is still being maintained.
There are some automated PRs to update dependencies still open.

I'd like to contribute to what I think is an issue with the format of the logs but first I'd like to see if someone could actually validate my changes, merge them and do a release.

Thanks,
Jorge

**Comment by niftylettuce** [comment]
I created https://cabinjs.com which is the recommended package now
