### ISSUE TITLE
Koa 2 support

### ISSUE THREAD

**Issue by tuhoojabotti** [koajs/bunyan-logger#7]
Would be nice to add a version for Koa 2 with promises! :)

**Comment by aheckmann** [comment]
Koa2 is holding in limbo until async await is available in Node so could be a while.

**Comment by aheckmann** [comment]
However, if all that's needed is Promise support, please open a PR.

**Comment by tuhoojabotti** [comment]
I'm using Koa 2 with TypeScript. TS compiles async functions into generators, which are already supported in Node.

I will check the changes that needs to be done and will write a PR when I have time. I'm using koa-convert for now, so it's not a big deal.

**Comment by ifraixedes** [comment]
This can be close

**Comment by sibelius** [comment]
how can I install the koa 2 version of this package from npm?

**Comment by ifraixedes** [comment]
@sibelius `npm install koa-bunyan-logger@next`

![screen shot 2016-08-25 at 08 30 32](https://cloud.githubusercontent.com/assets/1731633/17959094/72672c9a-6a9e-11e6-8895-cea8486e035d.png)

**Comment by sibelius** [comment]
Tks
